spring:
  application:
    name : web_IDE_for

  config:
    import: "optional:dotenv:.env"

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  server:
    port: 8080
    address: 0.0.0.0

clerk:
  jwks-url: https://clerk.webicapp.com/.well-known/jwks.json
  issuer: https://clerk.webicapp.com
  secret-key: ${CLERK_SECRET_KEY}
  webhook-secret-key: ${CLERK_WEBHOOK_SECRET_KEY}
